language: java

jdk:
  - openjdk11
  - oraclejdk11

branches:
  only:
  - main
  - development
  - development-new

before_script:
  - ls -la

script:
  - mvn clean package jacoco:report

after_success:
  - echo "Process terminated successfully"
